/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: amogusstrikesback2 (https://sketchfab.com/amogusstrikesback2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jailhouse-rock-b163d56af42f432b805ba6eae949b7ef
Title: jailhouse rock
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

export function JailHouse(props) {
  const { camera } = useThree();
  useEffect(() => {
    window.addEventListener("wheel", (ev) => {}, false);
  }, []);

  useFrame(() => {});
  const { nodes, materials } = useGLTF("./models/jailhouse/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.uranusprm004__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-8481.161, 1481.931, 12405.591]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.uranusprm003__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-1528.406, 323.863, 3366.809]}
          rotation={[0, -0.723, 0.974]}
          scale={100}
        />
        <mesh
          geometry={nodes.venusprm007__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-1540.101, 808.521, 5841.46]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 5]}
          scale={100}
        />
        <mesh
          geometry={nodes.venusprm006__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-1543.162, 809.11, 4581.793]}
          rotation={[-Math.PI / 2, 0, -0.283]}
          scale={100}
        />
        <mesh
          geometry={nodes.venusprm005__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-1544.74, 813.392, 3193.291]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.venusprm004__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-1541.862, 812.138, 1961.702]}
          rotation={[-Math.PI / 2, 0, -0.471]}
          scale={100}
        />
        <mesh
          geometry={nodes.venusprm003__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-23375.018, 807.409, -4297.464]}
          rotation={[-Math.PI / 2, 0, -0.283]}
          scale={100}
        />
        <mesh
          geometry={nodes.venusprm002__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-24864.324, 807.373, -4309.838]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.venusprm001__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-24868.27, 807.695, -2805.537]}
          rotation={[-Math.PI / 2, 0, -0.597]}
          scale={100}
        />
        <mesh
          geometry={nodes.venusprm__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-23363.592, 809.603, -2806.882]}
          rotation={[-Math.PI / 2, 0, 0.471]}
          scale={100}
        />
        <mesh
          geometry={nodes.uranusprm002__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-18843.633, 1484.945, 12263.641]}
          rotation={[0, 0, -2.325]}
          scale={100}
        />
        <mesh
          geometry={nodes.uranusprm001__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-11403.511, 462.881, 16401.006]}
          rotation={[0, -1.194, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.uranusprm__0.geometry}
          material={materials["uranus.prm.004__0"]}
          position={[-7577.017, 635.698, 16597.977]}
          rotation={[Math.PI, 0, -0.251]}
          scale={100}
        />
        <mesh
          geometry={nodes.jailhousew009_Material009_0.geometry}
          material={materials["Material.009"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.jailhousew008_Material003_0.geometry}
          material={materials["Material.003"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.jailhousew007_Material007_0.geometry}
          material={materials["Material.007"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.jailhousew006_Material008_0.geometry}
          material={materials["Material.008"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh geometry={nodes.jailhousew005_vcol_0.geometry} material={materials.vcol} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh
          geometry={nodes.jailhousew004_Material004_0.geometry}
          material={materials["Material.004"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.jailhousew003_Material002_0.geometry}
          material={materials["Material.002"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.jailhousew002_Material005_0.geometry}
          material={materials["Material.005"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.jailhousew000_Material006_0.geometry}
          material={materials["Material.006"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.jailhousew001_Material001_0.geometry}
          material={materials["Material.001"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/jailhouse/scene.gltf");
